### ISSUE TITLE
Issue in using given code for pretraining the model

### ISSUE THREAD

**Issue by jaineshdoshi** [allenai/PRIMER#19]
Hi,
I am trying to reproduce the pre-training experiment with the codebase here and ran into the following issue. 

Setup / Steps undertaken:

- Use [(LED-large)](https://huggingface.co/allenai/led-large-16384) as the base model to begin with.
- I used the preprocessed data given in the README file [here](https://storage.googleapis.com/primer_summ/processed_pretraining_data.tar.gz). 
- I modified the primer_hf_main.py a bit to add the [pretraining function](https://github.com/allenai/PRIMER/blob/main/script/primer_main.py#L366) from primer_main.py 
- I used the Pretrain Dataset class and dataloader functions defined [here](https://github.com/allenai/PRIMER/blob/daf9f42c3a495979ca4d2851a68b8c2dd3220ac3/script/dataloader.py#L155) in the dataloader.py file to load the preprocessed dataset, essentially replicating the exact pretrain function from the non HuggingFace primer file as is in the primer_hf_main.py file. 
- I provided other relevant args for the pretrain mode to my modified file and passed them to the pl.Trainer as shown in the other file with the same values 

Observations: 
- The PretrainDataset yields 2 values per sample in the batch even in the validation phase [here](https://github.com/allenai/PRIMER/blob/daf9f42c3a495979ca4d2851a68b8c2dd3220ac3/script/dataloader.py#L277).   
- Unlike the SummarizationIterDataset that yields 3 values in the validation mode [here](https://github.com/allenai/PRIMER/blob/daf9f42c3a495979ca4d2851a68b8c2dd3220ac3/script/dataloader.py#L451)
- Upon debugging, I realised that the [collate_fn](https://github.com/allenai/PRIMER/blob/daf9f42c3a495979ca4d2851a68b8c2dd3220ac3/script/dataloader.py#L454) when used with the pretraining mode with the PretrainDataset receives 2 variables per batch and always defaults to this [line](https://github.com/allenai/PRIMER/blob/daf9f42c3a495979ca4d2851a68b8c2dd3220ac3/script/dataloader.py#L479) raising an error in the validation sanity check test of the torch trainer. 

Firstly, I wanted to ask the authors @Wendy-Xiao if this is the expected behaviour and if I am taking some wrong assumptions here...?

My solution: 
To handle this, I added the tokenizer and decoded output string as the `tgt` string variable to be yielded (replicating the same behaviour in the SummarizationIterDataset iterator output using in the train mode) 

```
                    tgt = self.tokenizer.decode(data['tgt'], skip_special_tokens=True)
                    yield torch.tensor(data["src"]), torch.tensor(data["tgt"]), tgt

```

But this yields errors like these:
```
../aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [574,0,0], thread: [126,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:975: indexSelectLargeIndex: block: [574,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/PRIMER_train/script/primer_hf_main.py", line 982, in <module>
    pretrain(args)
  File "/PRIMER_train/script/primer_hf_main.py", line 456, in pretrain
    trainer.fit(model, train_dataloader, valid_dataloader)
  File "/Miniconda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 460, in fit
    self._run(model)
  File "/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 758, in _run
    self.dispatch()
  File "/Miniconda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 799, in dispatch
    self.accelerator.start_training(self)
  File "/Miniconda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/Miniconda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/Miniconda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in run_stage
    return self.run_train()
  File "/Miniconda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 844, in run_train
    self.run_sanity_check(self.lightning_module)
  File "/Miniconda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in run_sanity_check
    self.run_evaluation()
  File "/Miniconda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 967, in run_evaluation
    output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/Miniconda/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 174, in evaluation_step
    output = self.trainer.accelerator.validation_step(args)
  File "/Miniconda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 226, in validation_step
    return self.training_type_plugin.validation_step(*args)
  File "/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/PRIMER_train/script/primer_hf_main.py", line 291, in validation_step
    loss = self.shared_step(input_ids, output_ids)
  File "PRIMER_train/script/primer_hf_main.py", line 123, in shared_step
    lm_logits = self.forward(input_ids, output_ids)
  File "PRIMER_train/script/primer_hf_main.py", line 89, in forward
    outputs = self.model(
  File "/Miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/lib/python3.8/site-packages/transformers/models/led/modeling_led.py", line 2338, in forward
    outputs = self.led(
  File "/Miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/lib/python3.8/site-packages/transformers/models/led/modeling_led.py", line 2189, in forward
    encoder_outputs = self.encoder(
  File "/Miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Miniconda/lib/python3.8/site-packages/transformers/models/led/modeling_led.py", line 1733, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/Miniconda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Miniconda/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/Miniconda/lib/python3.8/site-packages/torch/nn/functional.py", line 2199, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: device-side assert triggered```
which I think are out of index errors in cuda for the embeddings. I checked that the new <doc-sep> token was included in the tokenizer correctly. 
(PS ignore the filepaths as they have been truncated here, but the code is configured to work as I have been able to finetune the base model on newer datasets)

Can anyone point me how to address these issue? 
Or how did you manage to pretrain the model from scratch using the author's code given here? 

Thanks a ton! :)

**Comment by Wendy-Xiao** [comment]
Hi there,

Thanks for your interest in our work, and your description is clear, so I can fully understand your current situation.

First of all, thanks for pointing out the problem with the validation output of the PretrainDataset, as I revised the code for training and testing after I pretrained the model, so there might be some incompatibilities with the pre-training process. And what you understand was totally correct, as I did not compute ROUGE score in pre-training phase, so although tgt is required as part of the input, it is not in use at all. I will revise the code to support it. 

And as for the problem when running the pre-training method, as I have not pre-trained the model from HF version of LED before, so I have not faced exactly the same problem. Based on the errors, it seems like it's an out-of-index problem. Could you double check the length of input and output of the batch causing this error, as well as the size of embedding layer of the LED-large model? It might be relevant to the settings of `max_input_len` and `max_output_len` in [this function](https://github.com/allenai/PRIMER/blob/daf9f42c3a495979ca4d2851a68b8c2dd3220ac3/script/dataloader.py#L534). 

Let me know if you still cannot find the problem.

**Comment by haisonle001** [comment]
@jaineshdoshi Hi, im working on pretraining step, too. In the paper, the config is said to be changed, im quite confused about how to change it. Do you change anything with your config file of led-large model or you just initialize the model with hf config file? Thank you so much.
<img width="417" alt="image" src="https://user-images.githubusercontent.com/81098528/190872199-11f42515-124d-40ab-94ac-04a0aa1cb215.png">

**Comment by haisonle001** [comment]
I managed to run the code of pretrain process.  I just change code of validation_step function. My code is down below. I dont know whether my code is good or bad. @Wendy-Xiao , @jaineshdoshi , Can you comment about my change? Thank you so much!

**    def validation_step(self, batch, batch_idx):
        for p in self.model.parameters():
            p.requires_grad = False
        if self.args.mode == "pretrain":
            input_ids, output_ids = batch
        else:
            input_ids, output_ids, tgt = batch
        loss = self.shared_step(input_ids, output_ids)
        if self.args.compute_rouge:
            result_batch = self.compute_rouge_batch(input_ids, output_ids, tgt)
            return {"vloss": loss, "rouge_result": result_batch}
        else:
            return {"vloss": loss}
**

@jaineshdoshi Furthermore, in the paper, the config is said to be changed, im quite confused about how to change it. Do you change anything with your config file of led-large model or you just initialize the model with hf config file? Is there any problem if i just use led-large and dont change anything? Thank you so much, look forwarding to receiving reply from you.
<img width="417" alt="image" src="https://user-images.githubusercontent.com/81098528/190872199-11f42515-124d-40ab-94ac-04a0aa1cb215.png">

**Comment by jaineshdoshi** [comment]
Hi,
@Wendy-Xiao 
Thanks for your prompt reply and appreciate your help here! 
I checked the batch max input/output lengths and they were set at 4096/1024 respectively, while the input samples too were truncated correctly with the code. I tried using different tokenizers (PRIMERA and led-large-16384) but still resulted in the same error. would yo have any other checks that I might be missing out on to handle this issue? 

Maybe, I can try to use the longformer/LED implementation from the [github](https://github.com/allenai/longformer#longformer) instead of the HuggingFace version but I recall I had faced some other errors initially with that too. 


@haisonle001 
I had also tried that approach to make the code here work but without luck as I ended up with the same error. 
If you wont mind, could you point me to what you did differently from the steps that I have mentioned above in order to get the code working for pretraining? 

I used the same configs of LED large as acquired from the hugging face model directly. I believe the authors can help you out better on this one. 

Cheers!

**Comment by haisonle001** [comment]
@jaineshdoshi  I use primer_main.py instead of primer_hf_main.py and i just changed code as above. I dont see much different between 2 files expect for how they loaded the model? You can try primer_main.py and do like what i did? may be it works.

**Comment by Wendy-Xiao** [comment]
Oh yeah, that makes sense! @jaineshdoshi. In the original code, I resize the embedding when initializing the model, and then I might remove those lines when I cleaned up the code.

you can try adding these lines into the __init__ function:
```
# The special token is added after each document in the pre-processing step.
self.tokenizer.add_special_tokens(
                {"additional_special_tokens": ["<doc-sep>"]}
            )
self.docsep_token_id = self.tokenizer.additional_special_tokens_ids[0]
self.model.resize_token_embeddings(len(self.tokenizer))
```

**Comment by jaineshdoshi** [comment]
Hi,
@Wendy-Xiao 
Thank you for the code updates! 
I just got it working yesterday by adding the lines that you mentioned above as soon as realized that the embedding dimensions weren't updated as per the new token. 

I do have a couple of questions on the model configuration. 

Looking at the [PRIMERA config.json](https://huggingface.co/allenai/PRIMERA/blob/main/config.json) files I do observe a few different parameters used for the LED, for example the attention window parameter in PRIMERA models config file is:
```
"attention_window": [
  512,
  512,
  512,
  512,
  512,
  512,
  512,
  512,
  512,
  512,
  512,
  512
  ],
```
while the same parameter in the [LED large model config file](https://huggingface.co/allenai/led-large-16384/blob/main/config.json) (that the paper says is the starting point for pretraining PRIMERA) on HF is 
```
"attention_window": [
  1024,
  1024,
  1024,
  1024,
  1024,
  1024,
  1024,
  1024,
  1024,
  1024,
  1024,
  1024
  ],
```
I am a bit confused as to if this was the LED that was used as a starting point for pretraining of PRIMERA. 
Can you shed some light on how do I get the correct configuration for the PRIMERA model to clear my confusion here? 

@haisonle001 
Thanks for helping out! 
I am hoping that the pretraining using the HF based code/models should still produce the same experiment as such. Will update you folks if I find any disparities!

**Comment by Wendy-Xiao** [comment]
Hi @jaineshdoshi 

Yes, as indicated in the paper(sec 4.1), we used different window size (512) and length limit for the input (4096) and output (1024) for PRIMERA. All the settings can be found in the paper (sec 4.1 and appendix A), and if there is no specification, we just used the same setting as LED. You can refer [PRIMERA config](https://huggingface.co/allenai/PRIMERA/blob/main/config.json).
